import { brand } from "../shared/brand";

export const openApiSpec = {
  openapi: "3.0.3",
  info: {
    title: `${brand.name} API`,
    version: "10.0.0",
    description: `${brand.tagline} Self-hosted backup orchestration with automatic restore proof.`
  },
  servers: [{ url: "/api" }],
  paths: {
    "/state": { get: { summary: "Dashboard state", tags: ["Dashboard"] } },
    "/summaries": { get: { summary: "App summaries with confidence scores", tags: ["Dashboard"] } },
    "/discovery": { get: { summary: "Host discovery", tags: ["Discovery"] } },
    "/repositories": { post: { summary: "Create vault", tags: ["Repositories"] } },
    "/google-drive/oauth/start": { post: { summary: "Start Google Drive OAuth connection", tags: ["Repositories"] } },
    "/google-drive/oauth/callback": { get: { summary: "Complete Google Drive OAuth connection", tags: ["Repositories"] } },
    "/apps": { post: { summary: "Register protected app", tags: ["Apps"] } },
    "/apps/{id}/jobs/{type}": { post: { summary: "Enqueue job", tags: ["Jobs"] } },
    "/apps/{id}/snapshots": { get: { summary: "List snapshots", tags: ["Snapshots"] }, delete: { summary: "Delete all snapshots for app", tags: ["Snapshots"] } },
    "/apps/{id}/snapshots/{snapshotId}/download": { get: { summary: "Download portable restored backup", tags: ["Snapshots"] } },
    "/apps/{id}/snapshots/{snapshotId}/contents": { get: { summary: "Browse snapshot file contents", tags: ["Snapshots"] } },
    "/apps/{id}/snapshots/{snapshotId}/compare": { get: { summary: "Compare snapshot with its parent", tags: ["Snapshots"] } },
    "/portable/import": { post: { summary: "Import and restore a portable backup", tags: ["Restore"] } },
    "/recovery-kit/export": { post: { summary: "Download encrypted BackupProof recovery kit", tags: ["Restore"] } },
    "/recovery-kit/import": { post: { summary: "Import encrypted BackupProof recovery kit", tags: ["Restore"] } },
    "/apps/{id}": { delete: { summary: "Remove protected app and all backups", tags: ["Apps"] } },
    "/jobs/clear": { post: { summary: "Clear completed job history", tags: ["Jobs"] } },
    "/apps/{id}/restore": { post: { summary: "Manual restore", tags: ["Restore"] } },
    "/apps/{id}/restore-preflight": { post: { summary: "Inspect restore readiness and destination risks", tags: ["Restore"] } },
    "/apps/{id}/dr-run": { post: { summary: "Disaster recovery run", tags: ["DR"] } },
    "/apps/{id}/dr-reports": { get: { summary: "List disaster recovery drill reports", tags: ["DR"] } },
    "/apps/{id}/dr-reports/{reportId}/download": { get: { summary: "Download disaster recovery drill report", tags: ["DR"] } },
    "/apps/{id}/runbook/download": { get: { summary: "Download app recovery runbook", tags: ["DR"] } },
    "/apps/{id}/evidence-bundle/download": { get: { summary: "Download recovery evidence bundle", tags: ["DR"] } },
    "/restore-destinations": { post: { summary: "Save restore destination template", tags: ["Restore"] } },
    "/apps/{id}/proof-report": { get: { summary: "Latest proof report", tags: ["Proof"] } },
    "/apps/{id}/proof-history": { get: { summary: "Restore proof history", tags: ["Proof"] } },
    "/demo/run": { post: { summary: "Green check demo", tags: ["Demo"] } },
    "/alerts/{id}/acknowledge": { post: { summary: "Acknowledge alert", tags: ["Alerts"] } },
    "/auth/login": { post: { summary: "Login", tags: ["Auth"] } },
    "/auth/logout": { post: { summary: "Logout", tags: ["Auth"] } },
    "/users": { post: { summary: "Create user (admin)", tags: ["Auth"] } },
    "/audit": { get: { summary: "Audit log export", tags: ["Compliance"] } },
    "/agents/register": { post: { summary: "Register fleet agent", tags: ["Fleet"] } },
    "/agents/heartbeat": { post: { summary: "Agent heartbeat", tags: ["Fleet"] } },
    "/engines/available": { get: { summary: "Detect installed optional engines", tags: ["Engines"] } },
    "/migrate/restic": { post: { summary: "Import existing Restic repo", tags: ["Migration"] } },
    "/migrate/kopia": { post: { summary: "Import existing Kopia repo", tags: ["Migration"] } }
  }
};
